version: "3.9"

services:
  kasm:
    #image: 'lscr.io/linuxserver/webtop:ubuntu-mate'
    #image: 'lscr.io/linuxserver/webtop:latest'
    #image: 'lscr.io/linuxserver/webtop'
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    security_opt:
      - seccomp:unconfined 
    shm_size: "2gb"  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - VNC_PASSWORD=abcd1234
      - ENABLE_CJK_FONT=1                         
      - KASM_PORT=443
    volumes:
      - /home/minhle711/kasmvnc-data:/config         
    ports:
      - "443:443"   
      - "8443:8443"    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
#      restart: unless-stopped
    
