services:
  webtop:
    image: 'lscr.io/linuxserver/webtop:ubuntu-mate'
    container_name: webtop
    security_opt:
      - 'seccomp:unconfined'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - SUBFOLDER=/
      - TITLE=Webtop
      - CUSTOM_USER=minhle711
      - PASSWORD=Minh123@/?!
      - 'DOCKER_MODS=linuxserver/mods:universal-package-install'
      - INSTALL_PACKAGES=font-noto-cjk
    volumes:
#      - 'webtop-config:/config'
      - '/home/minhle711/kasmvnc-data:/config'
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    devices:
#      - '/dev/dri:/dev/dri'
    shm_size: 1gb
    restart: unless-stopped
