services:
  kasm:
    #image: lscr.io/linuxserver/kasm:1.18.0
    #image: 'lscr.io/linuxserver/webtop:ubuntu-mate'
    image: 'lscr.io/linuxserver/webtop'
    container_name: kasm
    privileged: true                             
    security_opt:
      - apparmor:unconfined                      
    environment:
      - KASM_PORT=443
      - TZ=Asia/Ho_Chi_Minh
      - VNC_PASSWORD=abcd1234@                  
    volumes:
      - /home/minhle711/kasm-data:/opt                
      - /home/minhle711/kasm-profiles:/profiles      
    ports:
      - "3000:3000"                              
      - "8443:443"                               
    shm_size: "2gb"                              
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443"]
      interval: 30s
      timeout: 10s
      retries: 3
